apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: eurekaserver-sample
  namespace: my-apps
spec:
  ref:
    apiVersion: service-registry.spring.apps.tanzu.vmware.com/v1alpha1
    kind: EurekaServer
    name: eurekaserver-sample
    namespace: my-apps